### ISSUE TITLE
virtual display

### ISSUE THREAD

**Issue by djbr1** [Links2004/x6100-armbian#4]
QT GUI app needs a display to start.
Starting it with various "platform" options (eg. ./x6100_ui_v100 --platform offscreen   or vnc ) does not work properly.
Without recompiling it is not going to work with any desktop or window manager

Possible solution would be to create virtual (dummy) framebuffer device allowing GUI to start whereas main physical screen could be used by applications like flrig, fldigi, wsjtx.  Rig control would be through CAT

Existing configuration points to LCD

```

# eglfs_kms config files 
export QT_QPA_EGLFS_KMS_CONFIG=/etc/qtkmsconfig.json 


[root@XIEGU-x6100:/root]# cat /etc/qtkmsconfig.json 
{ 
"device": "/dev/dri/card1", 
"hwcursor": false, 
"pbuffers": true, 
"outputs": [ 
  { 
"name": "LCD", 
"mode": "800x480" 
  } 
] 
  } 
[root@XIEGU-x6100:/root]# ```

**Comment by djbr1** [comment]
Hi Markus

It is possible to start application without screen output

```[root@x6100:/etc]# cat  qtkmsconfig.json
{
    "device": "/dev/dri/renderD128",
    "headless": "800x480"
}
[root@x6100:/etc]#```

**Comment by Links2004** [comment]
headless is a good idea, had a look at the platform modes.
but since the APP requires openGL /EGL using the VNC backend is not possible.
you only get a black screen up on connect to the VNC server which does not help.

unfortunately button 4 is broken on my device. so no way to find the GPIO pin currently.
will Implement the kernel cmd line option for now

**Comment by Links2004** [comment]
Button 2 will start start the APP in headless in v0.0.3
